services:
  back-proxy:
    image: 'nginx:stable-alpine'
    container_name: task_nest_back-proxy
    ports:
      - '8081:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./back:/var/www/laravel
    depends_on:
      - back
    networks:
      - main-network 

  mysql:
    image: mysql:8.0
    container_name: task_nest_mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_nest
    networks:
      - main-network


  back:
    build:
      context: ./back
      target: back-base
    container_name: task_nest_back
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=task_nest
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./back:/var/www/laravel
    depends_on:
      - php-my-admin
    networks:
      - main-network

  front:
    build:
      context: ./front
      target: client-dev
    container_name: task_nest_front
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
      - ./front/package.json:/app/package.json
      - ./front/bun.lockb:/app/bun.lockb
      - /app/node_modules
    ports:
      - 8080:5173
    networks:
      - main-network

  php-my-admin:
    image: phpmyadmin
    container_name: task_nest_php-my-admin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8082:80
    depends_on:
      - mysql
    networks:
      - main-network

networks:
  main-network:

volumes:
  mysql-data:
